# Generated by Django 5.0.6 on 2024-06-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist_customer', to='petapp.pet'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderdate',
            field=models.DateField(default='2024-01-01', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='pincode',
            field=models.BigIntegerField(),
        ),
        migrations.AlterModelTable(
            name='orderdetail',
            table='orderdetail',
        ),
    ]
